### ISSUE TITLE
Add Catalonia ES-CT flag emoji

### ISSUE THREAD

**Issue by jmontane** [jdecked/twemoji#38]
While not encouraged, it's become common to have flags represent languages. Catalan being one of the most widespread spoken minority language in Europe, meaning it's supported in a lot of applications. Though, it doesn't have an emoji flag to represent it, which presents some annoying workarounds each time it needs to be added.

I'm requesting the flag from Catalonia to be added, similar to how Wales, England, and Scotland were. [Catalan emoji](https://emojipedia.org/flag-for-catalonia-esct/) (🏴󠁥󠁳󠁣󠁴󠁿) is just the same sort of thing, subdivision emoji in the Unicode standard, with encoding U+1F3F4 U+E0065 U+E0073 U+E0063 U+E0074 U+E007F

Other emoji libraries, like [OpenMoji](https://openmoji.org/library/#group=extras-unicode%2Fsubdivision-flag), support such kind of subdivision flag emoji.

I provide an .svg file. I'm the author of it. It can be used and added  to this Twemoji repo.

![1f3f4-e0065-e0073-e0063-e0074-e007f](https://github.com/jdecked/twemoji/assets/339645/ee3b6031-8926-437f-bb7f-754537cbf07b)
![1f3f4-e0065-e0073-e0063-e0074-e007f](https://github.com/jdecked/twemoji/assets/339645/8dd9a7d3-1c5d-4b2d-a92d-483a5c1de862)

related: https://github.com/twitter/twemoji/issues/574

**Comment by jdecked** [comment]
Thanks, but you'll have to take it up with Unicode. England, Scotland, and Wales are the only Recommended for General Interchange (RGI) subdivision flags. We only support RGI emoji.

**Comment by jdecked** [comment]
Personally, I'm not willing to pick and choose which subdivision flags we support. There's no good way to do it with flags because they are inherently political: if an emoji package adds one subdivision flag but not another, users can perceive that package as being politically biased even when that's not true in reality.

On the flip side, supporting all subdivision flags means nearly _doubling_ the size of the set (~3700 RGI emoji in Unicode 15.1, vs ~3600 subdivision flags). Even if we decided to support only RGI flags _plus_ those subdivision flags corresponding to distinct languages in the world, we'd still wind up with a gigantic number of new flags because there are many, many languages out there.

Flags are already amongst the lowest used emoji. As a small project (unlike WhatsApp), we need to choose wisely where we invest our limited time and effort. Maybe in the future this will change: on a personal level, I think it'd be really cool to have a wider emoji set with as much support as possible. But on a practical level with the resources we currently have, that's just not possible right now.

Even beyond the "we don't have the resources for this right now" aspect, there's the user experience: if we support emoji that most other vendors don't support, users copying text with Twemoji in them to send using other websites/apps get a weird experience. People shouldn't have to understand the intricacies of Unicode to have a good experience on the internet: emoji that display as intended in one place but not another creates confusion.

I get that it sucks to not have a flag that's useful to you represented in Twemoji. We occasionally get these requests from people in communities with flags that matter to them that aren't represented in RGI Unicode (or sometimes in Unicode at all), and I understand the frustration. But hopefully this explanation makes it a little clearer.

**Comment by joapuiib** [comment]
I would argue that this is not political, since there exists an own language behind that could benefit of having this emoji.

As an example, [Material for Mkdocs](https://squidfunk.github.io/mkdocs-material/) supports [a ton of languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/). Catalan, Galician and Basque are represented with the Spanish flag, when they are usually represented with their respective flags.
