### ISSUE TITLE
Shading and base color on Leftwards/Rightwards Pushing Hand does not match other hand emojis

### ISSUE THREAD

**Issue by Cynosphere** [jdecked/twemoji#62]
Its negligible on the skin tones unless you're looking at the shading closely, but the base color of the normal yellow stands out a lot.
![Showing all tones of Leftwards Pushing Hand compared to Wave](https://github.com/jdecked/twemoji/assets/1606710/66da896a-f2ac-488e-a999-19508de0fbad)
![Showing Leftwards and Rightwards Pushing Hand compared to other hand emojis in Discord's emoji picker](https://github.com/jdecked/twemoji/assets/1606710/3992b311-19c7-4740-859b-2511ac68748f)

**Comment by jdecked** [comment]
Yeah, the skin colours and skin shadows for pushing hands are slightly off right now unfortunately. We're in the process of fixing them and writing adding the exact colours to our style guide so it doesn't happen again.

(Style guide will be more widely publicized when we get the time to clean it up nicely since right now it's in rather disorganized meeting note form – after the holidays.)

**Comment by bsoap-cat** [comment]
This incorrect shade of yellow is also seen when contrasting the shaking face 🫨 with any other smiley emoji except for the emojis that dont use yellow skin
![image](https://github.com/jdecked/twemoji/assets/127647009/64f51487-40db-406c-ae45-2c3f21db77b6)
