### ISSUE TITLE
What's going on with TS types

### ISSUE THREAD

**Issue by Xstoudi** [jdecked/twemoji#72]
Hello,

I noticed `@twemoji/api` types seems to only export under `twemoji` module which is obviously not found as the package is `@twemoji/api`. Am I missing something?

**Comment by jdecked** [comment]
@Xstoudi feel free to PR a fix. As mentioned when the TS types were added to the repo, I don't personally use TS and thus have a pretty low chance of catching any TS-related errors. IMO the types should be moved back to the DefinitelyTyped repo, since I have generally no desire or time to maintain myself (given I don't use TS).
